### ISSUE TITLE
-X flag requires argument of the form importpath.name=value

### ISSUE THREAD

**Issue by paritosh90** [revel/cmd#50] opened 2016-06-15 12:48 UTC
I am getting following error on running revel app in development mode. I am posting logs below

```
INFO  2016/06/14 16:18:17 build.go:172: Cleaning dir tmp
INFO  2016/06/14 16:18:17 build.go:172: Cleaning dir routes
2016/06/14 16:18:17 reflect.go:728: Failed to generate name for field. Make sure the field name is valid.
2016/06/14 16:18:17 reflect.go:728: Failed to generate name for field. Make sure the field name is valid.
2016/06/14 16:18:17 reflect.go:728: Failed to generate name for field. Make sure the field name is valid.
INFO  2016/06/14 16:18:17 build.go:172: Cleaning dir tmp
INFO  2016/06/14 16:18:17 build.go:172: Cleaning dir routes
ERROR 2016/06/14 16:18:19 build.go:101: # api-core/app/tmp
/home/deploy/.gvm/gos/go1.6/pkg/tool/linux_amd64/link: -X flag requires argument of the form importpath.name=value

ERROR 2016/06/14 16:18:19 build.go:298: Failed to parse build errors:
 # api-core/app/tmp
/home/deploy/.gvm/gos/go1.6/pkg/tool/linux_amd64/link: -X flag requires argument of the form importpath.name=value
```

Also on running revel build I am getting following error

```
deploy@ip-172-xx-xx-x9 ~/api-core $ revel build api-core ./buiding1
~
~ revel! http://revel.github.io
~
INFO  2016/06/15 15:52:51 revel.go:365: Loaded module static
INFO  2016/06/15 15:52:51 revel.go:230: Initialized Revel v0.13.1 (2016-06-06) for >= go1.4
INFO  2016/06/15 15:52:51 build.go:172: Cleaning dir tmp
INFO  2016/06/15 15:52:51 build.go:172: Cleaning dir routes
2016/06/15 15:52:51 reflect.go:728: Failed to generate name for field. Make sure the field name is valid.
2016/06/15 15:52:51 reflect.go:728: Failed to generate name for field. Make sure the field name is valid.
2016/06/15 15:52:51 reflect.go:728: Failed to generate name for field. Make sure the field name is valid.
INFO  2016/06/15 15:52:51 build.go:172: Cleaning dir tmp
INFO  2016/06/15 15:52:51 build.go:172: Cleaning dir routes
TRACE 2016/06/15 15:52:51 build.go:94: Exec: [/home/deploy/.gvm/gos/go1.6/bin/go build -ldflags -X api-core/app.APP_VERSION "" -tags  -o /home/deploy/api-core/bin/revel.d/api-core/api-core api-core/app/tmp]
ERROR 2016/06/15 15:52:54 build.go:101: # api-core/app/tmp
/home/deploy/.gvm/gos/go1.6/pkg/tool/linux_amd64/link: -X flag requires argument of the form importpath.name=value

ERROR 2016/06/15 15:52:54 build.go:298: Failed to parse build errors:
 # api-core/app/tmp
/home/deploy/.gvm/gos/go1.6/pkg/tool/linux_amd64/link: -X flag requires argument of the form importpath.name=value
```

Please help me with this issue.
I am using v0.12.0

**Comment by jeevatkm** [comment] 2016-06-15 17:52
@paritosh90 Thanks for reporting. I'm glad to assist you.

First of all you're using `Revel v0.13.1` not v0.12.0, please see your log
```
INFO 2016/06/15 15:52:51 revel.go:230: Initialized Revel v0.13.1 (2016-06-06) for >= go1.4
```

Kindly cross check your controller method params type, because this could happen in that scenario
```
2016/06/15 15:52:51 reflect.go:728: Failed to generate name for field. Make sure the field name is valid.
```

Final one, this is surprise because I know this happens with golang `devel or tip` branch and `1.7-beta`. I'm not quiet sure how this is happening in Go 1.6; `v0.13.1` is verified against 1.6, please have a look [travis-ci build log](https://travis-ci.org/revel/revel/builds/135727838).

Can you please help me to reproduce this error in Go 1.6  `-X flag requires argument`?

**Comment by ottob** [comment] 2016-06-15 21:27
harness/build.go:80
-versionLinkerFlags := fmt.Sprintf("-X %s/app.APP_VERSION \"%s\"", revel.ImportPath, appVersion)
+versionLinkerFlags := fmt.Sprintf("-X %s/app.APP_VERSION=\"%s\"", revel.ImportPath, appVersion)

I would like to see this fixed now that go1.7beta has been released. The new format for `-X` has been supported since Go 1.5.

**Comment by jeevatkm** [comment] 2016-06-15 22:30
@ottob Thanks for your inputs. I will surely apply your suggestion on develop branch also when 1.7 gets release we can make Revel release too :)

What I would like to confirm or need your help or @paritosh90, does it break with Go `1.6`? based on this I will prioritize this fix and release time.

**Comment by paritosh90** [comment] 2016-06-16 02:28
@jeevatkm I am sorry. I have installed go using gvm and it installed devel version. Its working after installing go1.6. :)

**Comment by jeevatkm** [comment] 2016-06-16 02:42
No issues, I will be applying fix as part of #51. Thanks.

I'm closing this one.

**Closed by jeevatkm** 2016-06-16 02:42 UTC
Labels: discuss, support

**Comment by ottob** [comment] 2016-06-16 06:03
I would argue that it is a good idea to get this fix in before 1.7 final is released so users can test their revel applications with 1.7. Why wait?

**Comment by jeevatkm** [comment] 2016-06-16 18:12
@ottob Will do it before 1.7 final :)

**Comment by bejayoharen** [comment] 2016-09-23 16:26
I am seeing this issue with go 1.6. Is there a workaround?

$ revel version
~
~ revel! http://revel.github.io
~
Version(s):
   Revel v0.13.1 (2016-06-06)
   go1.6.2 darwin/amd64

**Comment by jeevatkm** [comment] 2016-09-23 16:30
This issue was fixed in #51. So take an updated revel/cmd

`go get -u github.com/revel/cmd/revel`

**Comment by bejayoharen** [comment] 2016-09-23 16:39
Okay, thanks. I was confused that the version number and release date were unchanged.

**Comment by jeevatkm** [comment] 2016-09-23 16:42
@bejayoharen no change in the framework side. just command line tool got updated for this issue.
