### ISSUE TITLE
After `go get` newest commit. `revel packag`e generates a run.sh with "-runMode <no value>"

### ISSUE THREAD

**Issue by Rcio** [revel/cmd#47] opened 2016-06-07 08:55 UTC
Hi,

My CI system build my project on every commit, since last build, my project refuse to start up because of this start up shell.

![6389b81d-9ed3-4497-9ac2-c8a9717f4e42](https://cloud.githubusercontent.com/assets/1480607/15851507/a8a58462-2ccf-11e6-882b-5943277a51f2.jpg)

Is that a bug just merge to master? Or just I make some mistakes.

**Comment by jeevatkm** [comment] 2016-06-07 15:05
@Rcio `revel package` & `revel build` supports environment/run mode in the latest release. For your reference PR #14 and [docs](http://revel.github.io/manual/tool.html#quick-ref). Please update your CI process accordingly. 

If you still face an issue, kindly provide us steps to reproduce this behavior.

**Comment by alkchr** [comment] 2016-06-07 15:45
@Rcio I cannot reproduce the described behaviour. Are you sure your `revel/cmd` is of the latest version (i.e. not just `revel/revel` was upgraded)? Command `go get -u github.com/revel/cmd/revel` must be called to achieve that.
Though, there is an issue. When running command `package`/`build` without the third optional argument it uses `dev` environment for me as the default. And I expect it to be `prod`.

**Comment by jeevatkm** [comment] 2016-06-07 19:14
@alkchr Thanks for verifying it, every revel command default to dev if not supplied. 

@Rcio please supply `runMode` for `revel package` command in your CI process.

**Comment by alkchr** [comment] 2016-06-08 04:16
@jeevatkm IMO that's a reasonable default for `revel run` but not for `revel build`. @revel/core, any thoughts?

**Comment by jeevatkm** [comment] 2016-06-08 17:52
@Rcio please share your response when you get a chance.

**Comment by jeevatkm** [comment] 2016-06-25 22:29
I'm closing this one.

**Closed by jeevatkm** 2016-06-25 22:29 UTC
Labels: support
